### ISSUE TITLE
Check your .tlu/properties.dat properties

### ISSUE THREAD

**Issue by NaturFront** [stephan-strate/teamspeak-league-update#3]
I cant install the bot and the update have a bug or anything. 

Here a screenshot: http://prntscr.com/ixqgua

**Comment by stephan-strate** [comment]
Try to download the newest version manually: https://github.com/stephan-strate/teamspeak-league-update/releases/download/3.0.1/teamspeak-league-update.jar and delete your .tlu folder.
I had a bug in Version 3.0.0, which caused this issue.

**Comment by NaturFront** [comment]
Where is the .tlu folder?

**Comment by stephan-strate** [comment]
It is in the same folder as your **teamspeak-league-update.jar**, it might be hidden by your system. Try to show hidden files and folders.

**Comment by NaturFront** [comment]
Thanks man!

**Comment by NaturFront** [comment]
All setups are right. 
Here a screen: http://prntscr.com/iy63p0

**Comment by NaturFront** [comment]
I reconnect with my second ID and dont get my rank.

**Comment by NaturFront** [comment]
I connect with the verifyed ID from bot. The ID is on the reconnect the same, what I mean.

**Comment by stephan-strate** [comment]
Difficult to tell where the problem is. You can send me your .tlu folder to my mail address (you can find my mail address on my profile, left side)

**Comment by stephan-strate** [comment]
I released a new version 3.0.2 with a small bugfix. This should fix your problems, you might need to delete your **.tlu/properties.dat**
